dist: trusty
sudo: required
language: python

python:
- 3.5
- 3.6

install:
 - sudo apt update
 - sudo apt -y install swig

script:
 - make test

before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
