dist: trusty
sudo: required
language: python

python:
- 3.4
- 3.5
- 3.6

install:
 - sudo apt update
 - sudo apt -y install swig

before_script:
 - cd $TRAVIS_BUILD_DIR/solvespace/exposed/

script:
 - make

before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
