#Travis-Ci
language: python

matrix:
  include:

    - os: linux
      sudo: required
      python: "3.5"
      dist: xenial

    - os: linux
      sudo: required
      python: "3.6"
      dist: xenial

    - os: linux
      sudo: required
      python: "3.7"
      dist: xenial

    - os: osx
      osx_image: xcode10
      language: generic
      env: PYTHON=35

    - os: osx
      osx_image: xcode10
      language: generic
      env: PYTHON=36

    - os: osx
      osx_image: xcode10
      language: generic
      env: PYTHON=37

# For OSX
before_install: |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
  curl -LO https://raw.githubusercontent.com/GiovanniBussi/macports-ci/master/macports-ci;
  source ./macports-ci install;
  yes | sudo port install python$PYTHON;
  sudo port select --set python3 python$PYTHON;
  python3 --version;
  fi

script:
 - make
 - python3 test_slvs.py

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
