# AppVeyor for Pyslvs-PyQt5
image: Visual Studio 2017

platform:
  - x64

environment:
  matrix:

    - MINGW_DIR: &mingw C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0
      MSYS_DIR: &msys2 C:\msys64
      PYTHON_DIR: C:\Python36-x64

    - MINGW_DIR: *mingw
      MSYS_DIR: *msys2
      PYTHON_DIR: C:\Python37-x64

skip_tags: true

install:
  # Environment variables.
  - set Path=%PYTHON_DIR%;%Path%
  - set Path=%PYTHON_DIR%\Scripts;%Path%
  - set Path=%MSYS_DIR%\usr\bin;%Path%
  - set Path=%MINGW_DIR%\mingw64\bin;%Path%

  # Show Python.
  - python --version
  - pip --version

  # Show tool kits.
  - gcc --version
  - mingw32-make --version

build_script:
  - mingw32-make

test_script:
  - python test_slvs.py
